### ISSUE TITLE
Hurl requires rack but doesn't mention it in the README

### ISSUE THREAD

**Issue by sjl** [defunkt/hurl#11]
Maybe this is obvious to Ruby people, but I don't really use Ruby at all so I didn't realize I needed to 'gem install rack' to get Hurl to work.

It's not mentioned in the README, and there are no errors shown when you run 'rake start' if you don't have rack installed -- you just don't get any server at localhost:9292.

**Comment by mislav** [comment]
I understand. Hurl is built on Sinatra, which in turn depends on Rack, so every ruby developer is aware that this stack needs Rack (and most of them already have it). But this dependency needs to be stressed out to others.

**Comment by sjl** [comment]
Yeah, I'm not a Ruby dev and I don't want to hack on Hurl itself, I just want to run it locally so I can use it to test an API that I'm not comfortable sharing with the world just yet.

**Comment by defunkt** [comment]
I thought installing the Sinatra RubyGem installed Rack. Apparently not! 

Sorry about that - I'll add it to the README.

**Comment by defunkt** [comment]
Mention rack as a dependency. Closed by 7e749b631f0ea2fb1a553378b00fc37f0bd4be14
