### ISSUE TITLE
Better error messages if missing xmllint or pygmentize

### ISSUE THREAD

**Issue by defunkt** [defunkt/hurl#12]
Currently you just get a "broken pipe" error.

**Comment by defunkt** [comment]
Better idea from sjl: 

```
actually, check upon startup and set a flag somewhere, then if it's not
successful you can skip highlighting the code so it doesn't break, and
display a warning like "syntax highlighting is not available because
pygments isn't installed"
```

**Comment by sjl** [comment]
Wow, that's definitely my run-on sentence of the day...

**Comment by josephholsten** [comment]
Seriously annoying. MacPorts installs py26-pygments into the path as pygmentize-2.6, and the only evidence of it was a flash that said "Weird response. Sorry." from hurl.js:190.

**Comment by defunkt** [comment]
Newest version of Hurl checks for xmllint, pygments, and simplejson. Shows a helpful error screen if it can't find one (or more) of them.
