### ISSUE TITLE
Mustache gem (>= 0.4.0) breaks app

### ISSUE THREAD

**Issue by dennmart** [defunkt/hurl#14]
I updated the Mustache gem on my server from 0.3.2 to 0.4.1 this morning, and Hurl stopped working completely. The same issue occurs in 0.4.0. Everything works fine when downgrading the gem to 0.3.2. I'm using Passenger / Ruby Enterprise 2009.10, but also tested with Thin, and had the same issues.

**Comment by defunkt** [comment]
This should be fixed in the forthcoming Mustache 0.4.2: http://github.com/defunkt/mustache/commit/1ff27cc1045e8eb344a9d4d4fbd45c24b032affa

**Comment by dennmart** [comment]
Yep, it works like a charm. Thanks!
