### ISSUE TITLE
^C only kills Redis, not Rack.

### ISSUE THREAD

**Issue by sjl** [defunkt/hurl#15]
This was mentioned in #13 but that was closed because the main problem was resolved.  When I run `rake start` in a Terminal and later hit `^C` the Redis process is killed but not the Rack server.  I have to run `killall ruby` from another Terminal to kill it.

**Comment by defunkt** [comment]
Can you copy / paste the output of these two commands:

```
rake --version
ruby --version
```

**Comment by sjl** [comment]
```
sjl at ecgtheow in ~
[11] $ rake --version
rake, version 0.8.7

sjl at ecgtheow in ~
[11] $ ruby --version
ruby 1.8.6 (2008-08-11 patchlevel 287) [universal-darwin9.0]
```

**Comment by yashh** [comment]
~/Desktop/hurl→rake --version
rake, version 0.8.3
~/Desktop/hurl→ruby --version
ruby 1.8.7 (2008-08-11 patchlevel 72) [universal-darwin10.0]

**Comment by mislav** [comment]
1. rake, version 0.8.7
2. ruby 1.8.7 (2009-06-12 patchlevel 174) [i686-darwin10.0.0], MBARI 0x6770, Ruby Enterprise Edition 20090928

**Comment by defunkt** [comment]
Redis is no longer required.
