### ISSUE TITLE
application/x-javascript response body not displayed

### ISSUE THREAD

**Issue by ablock** [defunkt/hurl#17]
When I request a file that's returned as MIME type application/x-javascript, the response header is displayed but the response content is not.

Example: paste "http://code.jquery.com/jquery-latest.js" into hurl.it.

**Comment by defunkt** [comment]
hurl is for api responses, like json, not files like javascript.

**Comment by defunkt** [comment]
actually, that's not true. i think we can fix this.

**Comment by defunkt** [comment]
okay, this works now: http://hurl.it/views/1dbfa810fade22f330c3fcf3238fabbbdf75ee64

it won't work with jquery yet, but that's a different bug.
