### ISSUE TITLE
Handling of gzip encoded responses

### ISSUE THREAD

**Issue by alexlehm** [defunkt/hurl#19]
with the add header feature, it is easy to check if a server supports deflate encoding, but it doesn't display anything if it does.

**Comment by defunkt** [comment]
can you give an example?

**Comment by alexlehm** [comment]
use URL twitter.com, add one header line with
Accept-Encoding gzip, deflate

the error message is string contains null byte

**Comment by defunkt** [comment]
Totally.

This should let us unzip the content

```
Zlib::GzipReader.new(StringIO.new(curl.body_str.to_s)).read
```

But I'm running into Pygments errors so maybe I'm not doing it right.

See https://gist.github.com/0bb76bf23a6254ab89d4

Anyone know how to handle this correctly?

**Comment by alexlehm** [comment]
are you sure that you are handling chunked encoding correctly before using deflate?

**Comment by defunkt** [comment]
I am sure of nothing, sir. I'll check.

**Comment by alexlehm** [comment]
twitter.com doesn't use chunked-encoding, so that is not the problem.
