### ISSUE TITLE
When the reply cannot be understood, some hints why would be useful

### ISSUE THREAD

**Issue by alexlehm** [defunkt/hurl#20]
When the reply cannot be displayed, displaying at least the header would be helpful.
Maybe the response can be displayed as hex dump.

**Comment by defunkt** [comment]
can you link to a reply that cannot be understood?

**Comment by mathiasbynens** [comment]
Well, I’m getting “Weird response. Sorry.” for http://mathiasbynens.be/

For some reason, `data.body = ""` for that request, so the `if` check on [line 205 of `public/js/hurl.js`](/defunkt/hurl/blob/master/public/js/hurl.js#L205) fails.

**Comment by alexlehm** [comment]
I get Weird response most of the time at http://www.arcor.de/

**Comment by defunkt** [comment]
In the arcor case I think it's Unicode. I don't think we're properly passing it to Pygments.

**Comment by alexlehm** [comment]
actually arcor.de uses UTF-8, but it also happens on pages that use latin1 (e.g. www.arcor.de/login/login.jsp)
