### ISSUE TITLE
basic auth breaks due to ruby's base64 implementation

### ISSUE THREAD

**Issue by progrium** [defunkt/hurl#25]
Ruby's Base64 library puts a newline not only at the end, but every 60 characters. This breaks HTTP headers (at least for servers that don't require \r), as well as the output in hurl's ui (changes from class 's' to 'nf' after 60 characters). 

I intend to submit a patch that strips newlines from the Base64 string before putting it in headers.

**Comment by progrium** [comment]
http://github.com/progrium/hurl/commit/7f391411f1b41f0d17f31b879b074344dca79053

**Comment by progrium** [comment]
It's likely this wasn't caught before because most user/pass combos are relatively short. I was dealing with one about 70 chars long before encoding.

**Comment by defunkt** [comment]
Merged, thanks!
