### ISSUE TITLE
HEAD method

### ISSUE THREAD

**Issue by challahc** [defunkt/hurl#26]
Dudes, you gotta add the HEAD method.  I guess this sounds kind of demanding... You don't have to add it, but I find it useful sometimes during troubleshooting. 

http://github.com/challahc/hurl/commit/ff492deec1d41ca7f8bebdf162de03ca2b42d202

**Comment by mazuhl** [comment]
+1 on this feature.

I use hurl a lot and this would be a useful addition.

**Comment by defunkt** [comment]
Done. Hurl is coming back to life and this will be in the new version. Thanks!
