### ISSUE TITLE
Can't Register at http://hurl.it/

### ISSUE THREAD

**Issue by fuentesjr** [defunkt/hurl#27]
For some reason I can't signup or login. I tried a few accounts with no success.

**Comment by kennethreitz** [comment]
+1

**Comment by defunkt** [comment]
New version coming soon — sorry about that!

**Comment by kennethreitz** [comment]
Awesome! We were thinking of hosting our own version of hurl.it at The Changelog, since this one has been down. But if you're going to push up a new one, no need :)

**Comment by defunkt** [comment]
http://hurl.it/

**Comment by kennethreitz** [comment]
You're the man.
