### ISSUE TITLE
PUT method 

### ISSUE THREAD

**Issue by macan** [defunkt/hurl#31]
On sending, it notifies "wrong number of arguments(0 for 1)".

**Comment by igorw** [comment]
That only happens when using a raw body, right? I fixed this in my pull request: https://github.com/defunkt/hurl/pull/30

**Comment by macan** [comment]
For PUT method, the post-body is always empty. And make_fields() returns [] for PUT method. In ruby 1.9.1 and curb 0.7.8, curl.send("http_put", *[]) doesn't work. FYI, the following patch works for me.
To igorw: your patch doesn't work for me. Anyway, thanks.

<pre><code>
--- hurl.rb.orig    2010-12-14 10:16:12.000000000 +0800
+++ hurl.rb 2010-12-14 10:01:52.000000000 +0800
@@ -224,7 +224,11 @@
 
     # post params from non-empty keys and values
     def make_fields(method, keys, values)
-      return [] unless method == 'POST'
+     if method == 'PUT'
+       return [""]
+      else
+        return [] unless method == 'POST'
+     end
 
       fields = []
       keys, values = Array(keys), Array(values)
</code></pre>

**Comment by igorw** [comment]
You also need to merge alcides PUT patch (his master branch) first, followed by my pull request: https://github.com/alcides/hurl

His patch allows sending a body with the put request.

**Comment by macan** [comment]
Thanks for point out alcides's branch. Your and his patch both works fine for me :)

**Comment by defunkt** [comment]
Added!
