### ISSUE TITLE
Hurl.it is down

### ISSUE THREAD

**Issue by davej** [defunkt/hurl#34]
Just a quick note in case you're not aware. Hurl.it is returning a 500 server error.

**Comment by defunkt** [comment]
Works for me.

**Comment by davej** [comment]
Yep, woking now. Must have been a temporary thing.

**Comment by kennethreitz** [comment]
Yeah, it was 500-ing the last two days.

**Comment by taf2** [comment]
down again?

**Comment by bymerej** [comment]
Seems to be fixed.

http://identi.ca/conversation/84452784
