### ISSUE TITLE
robots.txt?

### ISSUE THREAD

**Issue by benatkin** [defunkt/hurl#35]
If someone's running a search toolbar, it seems that when they click a permalink in /hurls, it seems that the search engine might index it. I observe that robots.txt at http://pastie.org/ has a robots.txt rule restricting /private but the same path at http://hurl.it/ returns a 404.
- http://pastie.org/robots.txt
- http://hurl.it/robots.txt

**Comment by defunkt** [comment]
Add robots.txt. Closed by 7a36e8b97b24779888554533ed9fc475e23455c8
