### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by noodl** [defunkt/hurl#39]
hurl.it is a really useful service but seems to have been down for much of the last few months.

Can I help you run it? I'm setting up a rackspace cloud HA cluster and hosting hurl.it would actually help with our http proxying and caching preparations.

Regardless, it'd be nice to see the site working again.

**Comment by noodl** [comment]
The site's running, here: http://46.38.173.225/

Feel free to update hurl.it to point to my copy of the service, or just close this ticket and I'll shut it down.

**Comment by DNNX** [comment]
It works now, I suppose the issue can be closed.

**Comment by tinsukE** [comment]
Guess we could reopen this, even the
http://46.38.173.225/
address is down

**Comment by noodl** [comment]
Sorry, I took my copy down when the real site came back up.

**Comment by caleywoods** [comment]
hurl.it down again but but the http://46.38.173.225/ site is working.

**Comment by defunkt** [comment]
http://hurl.it/ back up

**Comment by kennethreitz** [comment]
\o/

**Comment by caleywoods** [comment]
Thanks!

**Comment by apanzerj** [comment]
It's down again :-(

Getting a nginx bad gateway.

**Comment by matux** [comment]
Down... Hoping it'll come back up, it's a great service.
