### ISSUE TITLE
There is no brew install xmllint

### ISSUE THREAD

**Issue by mislav** [defunkt/hurl#5]
That brew recipe doesn't exists, nor can I find it with github search. But I do have `xmllint` command on my system, probably came with libxml2. However, there's no libxml2 homebrew recipe either...

**Comment by joshthecoder** [comment]
A side note here for ubuntu/debian users, use "apt-get install libxml2-utils" to install xmllint.

**Comment by jonhoman** [comment]
libxml2 for any Windows users, http://gnuwin32.sourceforge.net/packages/libxml2.htm

xmllint: http://code.google.com/p/xmllint/

I haven't tested either, but should be a good place to start.

**Comment by tomafro** [comment]
I found there was a libxml2 formula for homebrew, which I used when installing.  The documentation should be changed from 'brew install xmllint' to 'brew install libxml2'

**Comment by mhoofman** [comment]
<quote>The documentation should be changed from 'brew install xmllint' to 'brew install libxml2'</quote>

This was helpful. Thanks.

**Comment by defunkt** [comment]
Fixed! Thanks.

**Comment by chrismadrigal** [comment]
So I tryed `brew install libxml2` and this it what I'm getting:

`==> Downloading ftp://xmlsoft.org/libxml2/libxml2-2.9.1.tar.gz`

`curl: (7) couldn't connect to host`
`Trying a mirror...`
`==> Downloading http://xmlsoft.org/sources/libxml2-2.9.1.tar.gz`

**Comment by DrOzturk** [comment]
When I tried, it told me macs already has it, and I really had, so I used brew remove libxml2 to remove it back.
$ brew install libxml2
==> Downloading https://homebrew.bintray.com/bottles/libxml2-2.9.3.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libxml2-2.9.3.yosemite.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

Generally there are no consequences of this for you.

**Comment by bluntaz** [comment]
$ brew install libxml2
==> Downloading https://homebrew.bintray.com/bottles/libxml2-2.9.3.yosemite.bottle.tar.gz
